# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"
  config.vm.box_check_update = false

  config.vm.define "houbeidS" do |server|
    server.vm.hostname = "houbeidS"
    server.vm.network "private_network", ip: SERVER_IP

    server.vm.provider "virtualbox" do |v|
      v.name   = "houbeidS"
      v.cpus   = 1
      v.memory = 1024
    end

    server.vm.provision "shell",
      path: "scripts/install-k3s.sh",
      env: {
        "SERVER_IP" => SERVER_IP
      }
  end

end