# -*- mode: ruby -*-
# vi: set ft=ruby :

# =============================================================================
#   Vagrantfile - IoT Part 2 : K3s + 3 applications + Ingress
#   Server : houbeidS - 192.168.56.110 (server mode)
# =============================================================================

SERVER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"
  config.vm.box_check_update = false

  config.vm.define "houbeidS" do |server|
    server.vm.hostname = "houbeidS"
    server.vm.network "private_network", ip: SERVER_IP

    server.vm.provider "virtualbox" do |v|
      v.name   = "houbeidS"
      v.cpus   = 1
      v.memory = 1024
    end

    # Copier les fichiers de configuration dans la VM
    server.vm.provision "file", source: "confs/", destination: "/tmp/confs/"

    # Installation K3s + déploiement des apps
    server.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install -y curl

    echo "=== Installation K3s ==="
    SERVER_IP="192.168.56.110"

    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server \
        --bind-address=$SERVER_IP \
        --advertise-address=$SERVER_IP \
        --node-ip=$SERVER_IP \
        --write-kubeconfig-mode=644" sh -

    # Attendre K3s
    until kubectl get nodes 2>/dev/null | grep -q "Ready"; do
        sleep 5
    done

    #  Configuration kubeconfig automatique
    mkdir -p /home/vagrant/.kube
    cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
    chown vagrant:vagrant /home/vagrant/.kube/config
    chmod 600 /home/vagrant/.kube/config
    echo 'export KUBECONFIG=/home/vagrant/.kube/config' >> /home/vagrant/.bashrc

    echo "=== Déploiement des apps ==="
    kubectl apply -f /tmp/confs/

    kubectl wait --for=condition=available \
        --timeout=120s \
        deployment/app1 \
        deployment/app2 \
        deployment/app3

    kubectl get pods
    kubectl get ingress
    SHELL
  end

end
