# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"
K3S_TOKEN = "iottoken12345"

Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"
  config.vm.box_check_update = false

  # ========================= SERVER =========================
  config.vm.define "houbeidS" do |server|
    server.vm.hostname = "houbeidS"
    server.vm.network "private_network", ip: SERVER_IP

    server.vm.provider "virtualbox" do |v|
      v.name   = "houbeidS"
      v.cpus   = 1
      v.memory = 1024
    end

    server.vm.provision "shell",
      path: "scripts/install-server.sh",
      env: {
        "SERVER_IP" => SERVER_IP,
        "K3S_TOKEN" => K3S_TOKEN
      }
  end

  # ========================= WORKER =========================
  config.vm.define "houbeidSW" do |worker|
    worker.vm.hostname = "houbeidSW"
    worker.vm.network "private_network", ip: WORKER_IP

    worker.vm.provider "virtualbox" do |v|
      v.name   = "houbeidSW"
      v.cpus   = 1
      v.memory = 1024
    end

    worker.vm.provision "shell",
      path: "scripts/install-worker.sh",
      env: {
        "SERVER_IP" => SERVER_IP,
        "WORKER_IP" => WORKER_IP,
        "K3S_TOKEN" => K3S_TOKEN
      }
  end

end